ALTER TABLE reserver DROP CONSTRAINT IF EXISTS reserver_idcli_fkey;
ALTER TABLE reserver DROP CONSTRAINT IF EXISTS reserver_idvoit_fkey;
ALTER TABLE place DROP CONSTRAINT IF EXISTS place_idvoit_fkey;

ALTER TABLE voiture ALTER COLUMN idvoit DROP IDENTITY IF EXISTS;
ALTER TABLE voiture ALTER COLUMN idvoit TYPE VARCHAR(10) USING idvoit::VARCHAR;

ALTER TABLE client ALTER COLUMN idcli DROP IDENTITY IF EXISTS;
ALTER TABLE client ALTER COLUMN idcli TYPE VARCHAR(10) USING idcli::VARCHAR;

ALTER TABLE reserver ALTER COLUMN idreserv DROP IDENTITY IF EXISTS;
ALTER TABLE reserver ALTER COLUMN idreserv TYPE VARCHAR(10) USING idreserv::VARCHAR;
ALTER TABLE reserver ALTER COLUMN idvoit TYPE VARCHAR(10) USING idvoit::VARCHAR;
ALTER TABLE reserver ALTER COLUMN idcli TYPE VARCHAR(10) USING idcli::VARCHAR;

ALTER TABLE place ALTER COLUMN idvoit TYPE VARCHAR(10) USING idvoit::VARCHAR;

ALTER TABLE reserver ADD CONSTRAINT reserver_idvoit_fkey
    FOREIGN KEY (idvoit) REFERENCES voiture(idvoit);
ALTER TABLE reserver ADD CONSTRAINT reserver_idcli_fkey
    FOREIGN KEY (idcli) REFERENCES client(idcli);
ALTER TABLE place ADD CONSTRAINT place_idvoit_fkey
    FOREIGN KEY (idvoit) REFERENCES voiture(idvoit);