# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  packages: write

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Test
      run: mvn test
      
  build:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven    
    - name: Build with Maven
      run: mvn -B package -DskipTests
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar

  build_image:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Download JAR
      uses: actions/download-artifact@v4
      with:
        name: app-jar
        path: target
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/preserve-api:latest .
        docker tag ghcr.io/${{ github.repository_owner }}/preserve-api:latest \
                   ghcr.io/${{ github.repository_owner }}/preserve-api:${{ github.sha }}
    - name: Save Docker image
      run: docker save ghcr.io/${{ github.repository_owner }}/preserve-api:latest -o preserve-api.tar

    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: preserve-api.tar
  
  test_integration:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
      - name: Load docker image
        run: docker load -i preserve-api.tar
      - name: Launch docker compose
        run: docker compose -up
        env:
          DB_URL: ${{secrets.DB_URL}}
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      - name: Test app
        run: |
          echo "Attente du démarrage..."
          for i in {1..30}; do
            curl -s http://localhost:8080/api/voitures && break
            echo "Tentative $i..."
            sleep 5
          done
          
  push_image:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
    - name: Download Docker image
      uses: actions/download-artifact@v4
      with:
        name: docker-image

    - name: Load Docker image
      run: docker load -i preserve-api.tar

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/preserve-api:latest
        docker push ghcr.io/${{ github.repository_owner }}/preserve-api:${{ github.sha }}
      
      
